src/main/java/org/primefaces/cookbook/controller/chapter9/BarChartController.java
package org.primefaces.cookbook.controller.chapter9;

import org.primefaces.cookbook.utils.MessageUtil;
import org.primefaces.event.ItemSelectEvent;
import org.primefaces.model.chart.CartesianChartModel;
import org.primefaces.model.chart.ChartSeries;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 10/1/12
 */
@ManagedBean
@ViewScoped
public class BarChartController implements Serializable {

    private CartesianChartModel model;

    public BarChartController() {
        model = new CartesianChartModel();

        createModel();
    }

    private void createModel() {
        ChartSeries sales = new ChartSeries();
        sales.setLabel("Sales");
        sales.set("2004", 1000);
        sales.set("2005", 1170);
        sales.set("2006", 660);
        sales.set("2007", 1030);

        ChartSeries expenses = new ChartSeries();
        expenses.setLabel("Expenses");
        expenses.set("2004", 400);
        expenses.set("2005", 460);
        expenses.set("2006", 1120);
        expenses.set("2007", 540);

        model.addSeries(sales);
        model.addSeries(expenses);
    }

    public String getDatatipFormat() {
        return "<span style=\"display:none;\">%s</span><span>%s</span>";
    }

    public void itemSelect(ItemSelectEvent event) {
        MessageUtil.addInfoMessageWithoutKey("Item selected",
                "Series Index:" + event.getSeriesIndex() + ", Item Index: " + event.getItemIndex());
    }

    public CartesianChartModel getModel() {
        return model;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter9/BubbleChartController.java
package org.primefaces.cookbook.controller.chapter9;

import org.primefaces.model.chart.BubbleChartModel;
import org.primefaces.model.chart.BubbleChartSeries;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 10/3/12
 */
@ManagedBean
@ViewScoped
public class BubbleChartController implements Serializable {

    private BubbleChartModel model;

    public BubbleChartController() {
        createBubbleChart();
    }

    private void createBubbleChart() {
        model = new BubbleChartModel();

        model.add(new BubbleChartSeries("California", 3576, 170506, 4455));
        model.add(new BubbleChartSeries("Texas", 3248, 296259, 1710));
        model.add(new BubbleChartSeries("Florida", 2496,114422, 3104));
        model.add(new BubbleChartSeries("New York", 1422, 112347, 2885));
        model.add(new BubbleChartSeries("Georgia", 1403, 151746, 2179));
    }

    public BubbleChartModel getModel() {
        return model;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter9/DonutChartController.java
package org.primefaces.cookbook.controller.chapter9;

import org.primefaces.model.chart.DonutChartModel;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * User: mertcaliskan
 * Date: 10/3/12
 */
@ManagedBean
@ViewScoped
public class DonutChartController implements Serializable {

    private DonutChartModel model;

    public DonutChartController() {
        createDonutChart();
    }

    private void createDonutChart() {
        model = new DonutChartModel();

        Map<String, Number> circle1 = new LinkedHashMap<String, Number>();
        circle1.put("APPL", 150);
        circle1.put("IBM", 180);
        circle1.put("AMD", 30);
        circle1.put("INTC", 120);

        model.addCircle(circle1);

        Map<String, Number> circle2 = new LinkedHashMap<String, Number>();
        circle2.put("APPL", 180);
        circle2.put("IBM", 90);
        circle2.put("AMD", 100);
        circle2.put("INTC", 80);
        model.addCircle(circle2);

        Map<String, Number> circle3 = new LinkedHashMap<String, Number>();
        circle3.put("APPL", 210);
        circle3.put("IBM", 40);
        circle3.put("AMD", 80);
        circle3.put("INTC", 160);
        model.addCircle(circle3);
    }

    public DonutChartModel getModel() {
        return model;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter9/DynaImageController.java
package org.primefaces.cookbook.controller.chapter9;

import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.bean.ViewScoped;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 10/18/12
 */
@ManagedBean
@SessionScoped
public class DynaImageController implements Serializable {

    public StreamedContent getGraphicText() throws IOException {
        InputStream stream = this.getClass().getResourceAsStream("/chapter9/primefaces.jpg");
        return new DefaultStreamedContent(stream);
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter9/LineChartController.java
package org.primefaces.cookbook.controller.chapter9;

import org.primefaces.model.chart.CartesianChartModel;
import org.primefaces.model.chart.ChartSeries;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 9/18/12
 */
@ManagedBean
@ViewScoped
public class LineChartController implements Serializable {

    private CartesianChartModel model;

    private CartesianChartModel modelWithNull;

    public LineChartController() {
        model = new CartesianChartModel();
        modelWithNull = new CartesianChartModel();

        createModel();
        createModelWithNull();
    }

    private void createModelWithNull() {
        ChartSeries sales = new ChartSeries();
        sales.setLabel("Sales");
        sales.set("2004", 1000);
        sales.set("2005", null);
        sales.set("2006", null);
        sales.set("2007", 1030);

        ChartSeries expenses = new ChartSeries();
        expenses.setLabel("Expenses");
        expenses.set("2004", 400);
        expenses.set("2005", null);
        expenses.set("2006", 1120);
        expenses.set("2007", 540);

        modelWithNull.addSeries(sales);
        modelWithNull.addSeries(expenses);
    }

    private void createModel() {
        ChartSeries sales = new ChartSeries();
        sales.setLabel("Sales");
        sales.set("2004", 1000);
        sales.set("2005", 1170);
        sales.set("2006", 660);
        sales.set("2007", 1030);

        ChartSeries expenses = new ChartSeries();
        expenses.setLabel("Expenses");
        expenses.set("2004", 400);
        expenses.set("2005", 460);
        expenses.set("2006", 1120);
        expenses.set("2007", 540);

        model.addSeries(sales);
        model.addSeries(expenses);
    }

    public String getDatatipFormat() {
        return "<span style=\"display:none;\">%s</span><span>%s</span>";
    }
    
    public CartesianChartModel getModel() {
        return model;
    }

    public CartesianChartModel getModelWithNull() {
        return modelWithNull;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter9/MapController.java
package org.primefaces.cookbook.controller.chapter9;

import org.primefaces.cookbook.utils.MessageUtil;
import org.primefaces.event.map.OverlaySelectEvent;
import org.primefaces.model.chart.MeterGaugeChartModel;
import org.primefaces.model.map.*;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * User: mertcaliskan
 * Date: 10/10/12
 */
@ManagedBean
@ViewScoped
public class MapController implements Serializable {
                           
    private MapModel markerModel = new DefaultMapModel();
    private MapModel polylineModel = new DefaultMapModel();
    private MapModel polygonModel = new DefaultMapModel();
    private MapModel circleModel = new DefaultMapModel();

    private Marker selectedMarker;

    public MapController() {
        markerModel.addOverlay(new Marker(new LatLng(41.073399, 29.051971), "Bosphorus", "bosphorus.jpg"));
        markerModel.addOverlay(new Marker(new LatLng(41.118418, 29.134026), "Bosphorus", "bosphorus.jpg"));

        Polyline polyline = new Polyline();
        polyline.getPaths().add(new LatLng(41.073399, 29.051971));
        polyline.getPaths().add(new LatLng(41.118418, 29.134026));
        polyline.getPaths().add(new LatLng(41.027807, 29.049973));
        polylineModel.addOverlay(polyline);

        Polygon polygon = new Polygon();
        polygon.getPaths().add(new LatLng(41.073399, 29.051971));
        polygon.getPaths().add(new LatLng(41.118418, 29.134026));
        polygon.getPaths().add(new LatLng(41.027807, 29.049973));
        polygonModel.addOverlay(polygon);

        Circle circle = new Circle(new LatLng(41.073399, 29.051971), 5000);
        circleModel.addOverlay(circle);
    }

    public void onMarkerSelect(OverlaySelectEvent event) {
        Marker selectedMarker = (Marker) event.getOverlay();
        MessageUtil.addInfoMessageWithoutKey(selectedMarker.getTitle(), selectedMarker.getLatlng().toString());
    }

    public void selectMarker(OverlaySelectEvent event) {
        selectedMarker = (Marker) event.getOverlay();
    }

    public MapModel getMarkerModel() {
        return markerModel;
    }

    public MapModel getPolylineModel() {
        return polylineModel;
    }

    public MapModel getPolygonModel() {
        return polygonModel;
    }

    public MapModel getCircleModel() {
        return circleModel;
    }

    public Marker getSelectedMarker() {
        return selectedMarker;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter9/MeterGaugeController.java
package org.primefaces.cookbook.controller.chapter9;

import org.primefaces.model.chart.MeterGaugeChartModel;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * User: mertcaliskan
 * Date: 10/17/12
 */
@ManagedBean
@ViewScoped
public class MeterGaugeController implements Serializable {

    private MeterGaugeChartModel model;

    public MeterGaugeController() {
        List<Number> intervals = new ArrayList<Number>(){{
            add(22000);
            add(55000);
            add(70000);
        }};
        List<Number> ticks = new ArrayList<Number>(){{
            add(10000);
            add(20000);
            add(30000);
            add(50000);
            add(70000);
        }};
        model = new MeterGaugeChartModel(52200, intervals, ticks);
    }

    public MeterGaugeChartModel getModel() {
        return model;
    }

    public void setModel(MeterGaugeChartModel model) {
        this.model = model;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter9/OhlcChartController.java
package org.primefaces.cookbook.controller.chapter9;

import org.primefaces.model.chart.MeterGaugeChartModel;
import org.primefaces.model.chart.OhlcChartModel;
import org.primefaces.model.chart.OhlcChartSeries;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 10/17/12
 */
@ManagedBean
@ViewScoped
public class OhlcChartController implements Serializable {

    private OhlcChartModel model;

    public OhlcChartController() {
        model = new OhlcChartModel();

        model.add(new OhlcChartSeries(1, 136.01, 139.5, 134.53, 139.48));
        model.add(new OhlcChartSeries(2, 143.82, 144.56, 136.04, 136.97));
        model.add(new OhlcChartSeries(3, 136.47, 146.4, 136, 144.67));
        model.add(new OhlcChartSeries(4, 124.76, 135.9, 124.55, 135.81));
        model.add(new OhlcChartSeries(5, 123.73, 129.31, 121.57, 122.5));
        model.add(new OhlcChartSeries(6, 127.37, 130.96, 119.38, 122.42));
        model.add(new OhlcChartSeries(7, 128.24, 133.5, 126.26, 129.19));
        model.add(new OhlcChartSeries(8, 122.9, 127.95, 122.66, 127.24));
        model.add(new OhlcChartSeries(9, 121.73, 127.2, 118.6, 123.9));
        model.add(new OhlcChartSeries(10, 120.01, 124.25, 115.76, 123.42));
        model.add(new OhlcChartSeries(11, 114.94, 120, 113.28, 119.57));
        model.add(new OhlcChartSeries(12, 104.51, 116.13, 102.61, 115.99));
        model.add(new OhlcChartSeries(13, 102.71, 109.98, 101.75, 106.85));
        model.add(new OhlcChartSeries(14, 96.53, 103.48, 94.18, 101.59));
        model.add(new OhlcChartSeries(15, 84.18, 97.2, 82.57, 95.93));
        model.add(new OhlcChartSeries(16, 88.12, 92.77, 82.33, 85.3));
        model.add(new OhlcChartSeries(17, 91.65, 92.92, 86.51, 89.31));
        model.add(new OhlcChartSeries(18, 96.87, 97.04, 89, 91.2));
        model.add(new OhlcChartSeries(19, 100, 103, 95.77, 99.16));
        model.add(new OhlcChartSeries(20, 89.1, 100, 88.9, 99.72));
        model.add(new OhlcChartSeries(21, 88.86, 95, 88.3, 90.13));
        model.add(new OhlcChartSeries(22, 81.93, 90, 78.2, 88.36));
        model.add(new OhlcChartSeries(23, 90.46, 90.99, 80.05, 82.33));
        model.add(new OhlcChartSeries(24, 93.17, 97.17, 90.04, 90.58));
    }

    public String getDatatipFormat() {
        return "<table>" +
               "<tr><td>date:</td><td>%s</td></tr>" +
               "<tr><td>open:</td><td>%s</td></tr>" +
               "</table>";
    }

    public OhlcChartModel getModel() {
        return model;
    }

    public void setModel(OhlcChartModel model) {
        this.model = model;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter9/PieChartController.java
package org.primefaces.cookbook.controller.chapter9;

import org.primefaces.model.chart.PieChartModel;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 10/2/12
 */
@ManagedBean
@ViewScoped
public class PieChartController implements Serializable {

    private PieChartModel model;
    private PieChartModel liveChartModel;

    public PieChartController() {
        createPieModel();
    }

    private void createPieModel() {
        model = new PieChartModel();

        model.set("Work", 11);
        model.set("Eat", 2);
        model.set("Commute", 2);
        model.set("Watch TV", 2);
        model.set("Sleep", 7);

        liveChartModel = new PieChartModel();

        liveChartModel.set("Candidate 1", 540);
        liveChartModel.set("Candidate 2", 325);
    }

    public PieChartModel getModel() {
        return model;
    }

    public PieChartModel getLivePieModel() {
        int random1 = (int)(Math.random() * 1000);
        int random2 = (int)(Math.random() * 1000);

        liveChartModel.getData().put("Candidate 1", random1);
        liveChartModel.getData().put("Candidate 2", random2);

        return liveChartModel;
    }
}

src/main/webapp/views/chapter9/barChart.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Charting with Bar</h3>
        <p:growl id="growl" showDetail="true"/>
        <h:panelGrid columns="2" cellpadding="5">

            <h:outputText value="Simple" />
            <p:barChart value="#{barChartController.model}" style="height:250px" title="Company Performance" />

            <h:outputText value="With Animation" />
            <p:barChart value="#{barChartController.model}" style="height:250px" animate="true" />

            <h:outputText value="With Zooming - Select Region" />
            <p:barChart value="#{barChartController.model}" style="height:250px" zoom="true" />

            <h:outputText value="With Legends" />
            <p:barChart value="#{barChartController.model}" style="height:250px" legendPosition="nw" />

            <h:outputText value="With Orientation" />
            <p:barChart value="#{barChartController.model}" style="height:250px" orientation="horizontal" />

            <h:outputText value="With Labels on Axes" />
            <p:barChart value="#{barChartController.model}" style="height:250px" xaxisLabel="Year" yaxisLabel="Amount" />

            <h:outputText value="With Angles on Axes" />
            <p:barChart value="#{barChartController.model}" style="height:250px" xaxisAngle="45" yaxisAngle="45"  />

            <h:outputText value="With Series Colors" />
            <p:barChart value="#{barChartController.model}" style="height:250px" seriesColors="FF0000,00FF00" legendPosition="nw" />

            <h:outputText value="With Customized Data Tips" />
            <p:barChart value="#{barChartController.model}" style="height:250px" showDatatip="true" datatipFormat="#{barChartController.datatipFormat}" />

            <h:outputText value="With Stacked Bars" />
            <p:barChart value="#{barChartController.model}" style="height:250px" title="Company Performance" stacked="true" />

        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter9/bubbleChart.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Charting with Bubble</h3>
        <p:growl id="growl" showDetail="true"/>
        <h:panelGrid columns="2" cellpadding="5">

            <h:outputText value="Simple" />
            <p:bubbleChart value="#{bubbleChartController.model}" style="height:250px"
                           xaxisLabel="Number of Fatal Crashes" yaxisLabel="Public Road Mileage" />

            <h:outputText value="With Angles on Axes" />
            <p:bubbleChart value="#{bubbleChartController.model}" style="height:250px" xaxisAngle="45" yaxisAngle="45" />

            <h:outputText value="With Gradient and Alpha" />
            <p:bubbleChart value="#{bubbleChartController.model}" style="height:250px" bubbleGradients="true" bubbleAlpha="0.7" />

            <h:outputText value="With Series Colors" />
            <p:bubbleChart value="#{bubbleChartController.model}" style="height:250px" seriesColors="FF0000,00FF00,0000FF,F0F0F0,0F0F0F" />

        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter9/chartInteraction.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Interacting with charts by AJAX</h3>
        <p:growl id="growl" showDetail="true" />
        <h:panelGrid columns="2" cellpadding="5">

            <h:outputText value="With AJAX Behavior Event" />
            <p:barChart id="withAjax" value="#{barChartController.model}" style="height:250px">
                <p:ajax event="itemSelect" listener="#{barChartController.itemSelect}" update="growl" />
            </p:barChart>

        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter9/donutChart.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Charting with Donut</h3>
        <p:growl id="growl" showDetail="true"/>
        <h:panelGrid columns="2" cellpadding="5">

            <h:outputText value="Simple" />
            <p:donutChart value="#{donutChartController.model}" style="height:250px" title="Stocks by Year" legendPosition="nw" />

            <h:outputText value="With Series Colors" />
            <p:donutChart value="#{donutChartController.model}" style="height:250px" seriesColors="FF0000,00FF00,0000FF,F0F0F0,0F0F0F" legendPosition="nw" />

            <h:outputText value="With Adjusted Visual" />
            <p:donutChart value="#{donutChartController.model}" style="height:250px" sliceMargin="5" fill="false" />

        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter9/dynaImage.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Creating dynamic image streaming programmatically</h3>
        <p:growl id="growl" showDetail="true"/>
        <h:panelGrid columns="2" cellpadding="5">

            <h:outputText value="Simple" />
            <p:graphicImage value="#{dynaImageController.graphicText}" />

        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter9/lineChart.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Charting with Line</h3>
        <p:growl id="growl" showDetail="true"/>
        <h:panelGrid columns="2" cellpadding="5">

            <h:outputText value="Simple" />
            <p:lineChart value="#{lineChartController.model}" style="height:250px" title="Company Performance" />

            <h:outputText value="With Legends" />
            <p:lineChart value="#{lineChartController.model}" style="height:250px" legendPosition="nw" />

            <h:outputText value="With Animation" />
            <p:lineChart value="#{lineChartController.model}" style="height:250px" legendPosition="nw" animate="true" />

            <h:outputText value="With Zooming - Select Region" />
            <p:lineChart value="#{lineChartController.model}" style="height:250px" legendPosition="nw" zoom="true" />

            <h:outputText value="With Min-Max on Axes" />
            <p:lineChart value="#{lineChartController.model}" style="height:250px" minY="400" maxY="800" />

            <h:outputText value="With Labels on Axes" />
            <p:lineChart value="#{lineChartController.model}" style="height:250px" xaxisLabel="Year" yaxisLabel="Amount" />

            <h:outputText value="With Angles on Axes" />
            <p:lineChart value="#{lineChartController.model}" style="height:250px" xaxisAngle="45" yaxisAngle="45"  />

            <h:outputText value="With Series Colors" />
            <p:lineChart value="#{lineChartController.model}" style="height:250px" seriesColors="FF0000,00FF00" legendPosition="nw" />

            <h:outputText value="With Discrete Lining" />
            <p:lineChart value="#{lineChartController.modelWithNull}" style="height:250px" breakOnNull="false" />

            <h:outputText value="With Customized Data Tips" />
            <p:lineChart value="#{lineChartController.model}" style="height:250px" showDatatip="true" datatipFormat="#{lineChartController.datatipFormat}" />

            <h:outputText value="With Filled Under lines" />
            <p:lineChart value="#{lineChartController.model}" style="height:250px" fill="true" />

            <h:outputText value="With Stacked lines" />
            <p:lineChart value="#{lineChartController.model}" style="height:250px" stacked="true" />

        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter9/meterGaugeChart.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Charting with Meter Gauge</h3>
        <p:growl id="growl" showDetail="true"/>
        <h:panelGrid columns="2" cellpadding="5">

            <h:outputText value="Simple" />
            <p:meterGaugeChart id="simple" value="#{meterGaugeController.model}" style="height:250px" label="km/h" title="Title" />

            <h:outputText value="Custom" />
            <p:meterGaugeChart id="custom" value="#{meterGaugeController.model}" style="height:250px"
                                label="tons" title="Metric Tons Per Year"
                                showTickLabels="false" labelHeightAdjust="-20"
                                intervalOuterRadius="60" />

        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter9/pieChart.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Charting with Pie</h3>
        <p:growl id="growl" showDetail="true"/>
        <h:panelGrid columns="2" cellpadding="5">

            <h:outputText value="Simple" />
            <p:pieChart value="#{pieChartController.model}" style="height:250px" title="Hours per Day" />

            <h:outputText value="With Legends" />
            <p:pieChart value="#{pieChartController.model}" style="height:250px" legendPosition="nw" />

            <h:outputText value="With Series Colors" />
            <p:pieChart value="#{pieChartController.model}" style="height:250px" seriesColors="FF0000,00FF00,0000FF,F0F0F0,0F0F0F" legendPosition="nw" />

            <h:outputText value="With Data Labels" />
            <p:pieChart value="#{pieChartController.model}" style="height:250px" showDataLabels="true" dataFormat="percent" />

            <h:outputText value="With Adjusted Visual" />
            <p:pieChart value="#{pieChartController.model}" style="height:250px" sliceMargin="5" diameter="200" fill="false" />

        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter9/pollingChart.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Live Data updating of charts with polling</h3>
        <p:growl id="growl" showDetail="true"/>

        <h:panelGrid columns="3" cellpadding="5">

            <h:outputText value="Live Update" />
            <p:poll interval="3" update="live" />
            <p:pieChart id="live" value="#{pieChartController.livePieModel}" style="height:250px" />

        </h:panelGrid>

    </ui:define>
</ui:composition>