src/main/java/org/primefaces/cookbook/model/chapter12/BookProperty.java
package org.primefaces.cookbook.model.chapter12;

import java.io.Serializable;

import java.text.SimpleDateFormat;

import java.util.Date;


/**
 * BookProperty
 *
 * @author Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
public class BookProperty implements Serializable {

    private static final long serialVersionUID = 20120521L;

    private String name;
    private Object value;
    private boolean required;

    public BookProperty(String name, boolean required) {
        this.name = name;
        this.required = required;
    }

    public BookProperty(String name, Object value, boolean required) {
        this.name = name;
        this.value = value;
        this.required = required;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Object getValue() {
        return value;
    }

    public Object getFormattedValue() {
        if (value instanceof Date) {
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("d MMM yyyy");

            return simpleDateFormat.format(value);
        }

        return value;
    }

    public void setValue(Object value) {
        this.value = value;
    }

    public boolean isRequired() {
        return required;
    }

    public void setRequired(boolean required) {
        this.required = required;
    }
}

src/main/java/org/primefaces/cookbook/model/chapter12/Circle.java
package org.primefaces.cookbook.model.chapter12;

import java.io.Serializable;


/**
 * Circle
 *
 * @author Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
public class Circle implements Serializable {

    private static final long serialVersionUID = 20111020L;

    private int radius;
    private String backgroundColor;
    private String borderColor;
    private double scaleFactor;

    public final int getRadius() {
        return radius;
    }

    public final void setRadius(int radius) {
        this.radius = radius;
    }

    public final String getBackgroundColor() {
        return backgroundColor;
    }

    public final void setBackgroundColor(String backgroundColor) {
        this.backgroundColor = backgroundColor;
    }

    public final String getBorderColor() {
        return borderColor;
    }

    public final void setBorderColor(String borderColor) {
        this.borderColor = borderColor;
    }

    public final double getScaleFactor() {
        return scaleFactor;
    }

    public final void setScaleFactor(double scaleFactor) {
        this.scaleFactor = scaleFactor;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter12/CodeMirrorController.java
package org.primefaces.cookbook.controller.chapter12;

import java.io.Serializable;

import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;


/**
 * CodeMirrorController
 *
 * @author Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
@ManagedBean
@ViewScoped
public class CodeMirrorController implements Serializable {

    private String content;
    private String mode = "javascript";

    public CodeMirrorController() {
        content = "function test() { console.log('test'); }";
    }

    public void changeMode() {
        if (mode.equals("css")) {
            mode = "javascript";
        } else {
            mode = "css";
        }
    }

    public List<String> complete(String token, String context) {
        ArrayList<String> suggestions = new ArrayList<String>();

        suggestions.add("context: " + context);
        suggestions.add("token: " + token);

        return suggestions;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getMode() {
        return mode;
    }

    public void setMode(String mode) {
        this.mode = mode;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter12/DynaFormController.java
package org.primefaces.cookbook.controller.chapter12;

import org.primefaces.context.RequestContext;

import org.primefaces.cookbook.model.chapter12.BookProperty;

import org.primefaces.extensions.model.dynaform.DynaFormControl;
import org.primefaces.extensions.model.dynaform.DynaFormLabel;
import org.primefaces.extensions.model.dynaform.DynaFormModel;
import org.primefaces.extensions.model.dynaform.DynaFormRow;

import java.io.Serializable;

import java.util.ArrayList;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;


/**
 * DynaFormController
 *
 * @author Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
@ManagedBean
@ViewScoped
public class DynaFormController implements Serializable {

    private static final long serialVersionUID = 20120423L;

    private static List<SelectItem> LANGUAGES = new ArrayList<SelectItem>();

    private DynaFormModel model;

    public DynaFormController() {
        model = new DynaFormModel();

        // add rows, labels and editable controls
        // set relationship between label and editable controls
        // to support outputLabel with "for" attribute

        // 1. row
        DynaFormRow row = model.createRegularRow();

        DynaFormLabel label11 = row.addLabel("Author", 1, 1);
        DynaFormControl control12 = row.addControl(new BookProperty("Author", true), "input", 1, 1);
        label11.setForControl(control12);

        DynaFormLabel label13 = row.addLabel("ISBN", 1, 1);
        DynaFormControl control14 = row.addControl(new BookProperty("ISBN", true), "input", 1, 1);
        label13.setForControl(control14);

        // 2. row
        row = model.createRegularRow();

        DynaFormLabel label21 = row.addLabel("Title", 1, 1);
        DynaFormControl control22 = row.addControl(new BookProperty("Title", false), "input", 3, 1);
        label21.setForControl(control22);

        // 3. row
        row = model.createRegularRow();

        DynaFormLabel label31 = row.addLabel("Publisher", 1, 1);
        DynaFormControl control32 = row.addControl(new BookProperty("Publisher", false), "input", 1, 1);
        label31.setForControl(control32);

        DynaFormLabel label33 = row.addLabel("Published on", 1, 1);
        DynaFormControl control34 = row.addControl(new BookProperty("Published on", false), "calendar", 1, 1);
        label33.setForControl(control34);

        // 4. row
        row = model.createRegularRow();

        DynaFormLabel label41 = row.addLabel("Language", 1, 1);
        DynaFormControl control42 = row.addControl(new BookProperty("Language", false), "select", 1, 1);
        label41.setForControl(control42);

        DynaFormLabel label43 = row.addLabel("Description", 1, 2);
        DynaFormControl control44 = row.addControl(new BookProperty("Description", false), "textarea", 1, 2);
        label43.setForControl(control44);

        // 5. row
        row = model.createRegularRow();

        DynaFormLabel label51 = row.addLabel("Rating", 1, 1);
        DynaFormControl control52 = row.addControl(new BookProperty("Rating", 3, true), "rating", 1, 1);
        label51.setForControl(control52);
    }

    public DynaFormModel getModel() {
        return model;
    }

    public List<BookProperty> getBookProperties() {
        if (model == null) {
            return null;
        }

        List<BookProperty> bookProperties = new ArrayList<BookProperty>();
        for (DynaFormControl dynaFormControl : model.getControls()) {
            bookProperties.add((BookProperty) dynaFormControl.getData());
        }

        return bookProperties;
    }

    public String submitForm() {
        FacesMessage.Severity sev = FacesContext.getCurrentInstance().getMaximumSeverity();
        boolean hasErrors = ((sev != null) && (FacesMessage.SEVERITY_ERROR.compareTo(sev) >= 0));

        RequestContext requestContext = RequestContext.getCurrentInstance();
        requestContext.addCallbackParam("isValid", !hasErrors);

        return null;
    }

    public List<SelectItem> getLanguages() {
        if (LANGUAGES.isEmpty()) {
            LANGUAGES.add(new SelectItem("en", "English"));
            LANGUAGES.add(new SelectItem("de", "German"));
            LANGUAGES.add(new SelectItem("ru", "Russian"));
            LANGUAGES.add(new SelectItem("tr", "Turkish"));
        }

        return LANGUAGES;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter12/ImageController.java
package org.primefaces.cookbook.controller.chapter12;

import org.primefaces.extensions.event.ResizeEvent;
import org.primefaces.extensions.event.RotateEvent;

import java.io.Serializable;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;


/**
 * ImageController
 *
 * @author Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
@ManagedBean
@ViewScoped
public class ImageController implements Serializable {

    public void rotateListener(RotateEvent e) {
        FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Image rotated", "Degree:" + e.getDegree());

        FacesContext.getCurrentInstance().addMessage(null, msg);
    }

    public void resizeListener(ResizeEvent e) {
        FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Image resized",
                "Width:" + e.getWidth() + ", Height: " + e.getHeight());

        FacesContext.getCurrentInstance().addMessage(null, msg);
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter12/InputNumberController.java
package org.primefaces.cookbook.controller.chapter12;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;


/**
 * InputNumberController
 *
 * @author Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
@ManagedBean
@ViewScoped
public class InputNumberController implements Serializable {

    private Double input1 = 0.0;
    private Double input2 = 0.0;
    private Double input3 = 0.0;
    private Double input4 = 0.0;

    public Double getInput1() {
        return input1;
    }

    public void setInput1(Double input1) {
        this.input1 = input1;
    }

    public Double getInput2() {
        return input2;
    }

    public void setInput2(Double input2) {
        this.input2 = input2;
    }

    public Double getInput3() {
        return input3;
    }

    public void setInput3(Double input3) {
        this.input3 = input3;
    }

    public Double getInput4() {
        return input4;
    }

    public void setInput4(Double input4) {
        this.input4 = input4;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter12/RemoteCommandController.java
package org.primefaces.cookbook.controller.chapter12;

import org.primefaces.cookbook.model.chapter12.Circle;

import java.util.Date;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;


/**
 * RemoteCommandController
 *
 * @author Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
@ManagedBean
@RequestScoped
public class RemoteCommandController {

    private String subject;
    private Date date;
    private Circle circle;

    public void printMethodParams(String subject, Date date, Circle circle) {
        FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Parameters",
                "Subject: " + subject + ", Date: " + date + ", Circle - backgroundColor: " +
                circle.getBackgroundColor());

        FacesContext.getCurrentInstance().addMessage(null, msg);
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Circle getCircle() {
        return circle;
    }

    public void setCircle(Circle circle) {
        this.circle = circle;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter12/TimelineController.java
package org.primefaces.cookbook.controller.chapter12;

import org.primefaces.extensions.model.timeline.DefaultTimeLine;
import org.primefaces.extensions.model.timeline.DefaultTimelineEvent;
import org.primefaces.extensions.model.timeline.Timeline;

import java.io.Serializable;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import javax.annotation.PostConstruct;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;


/**
 * TimelineController
 *
 * @author Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
@ManagedBean
@ViewScoped
public class TimelineController implements Serializable {

    private List<Timeline> timelines;

    private String eventStyle = "dot";
    private String axisPosition = "bottom";

    @PostConstruct
    public void initialize() {
        timelines = new ArrayList<Timeline>();

        Calendar cal = Calendar.getInstance();
        Timeline timeline = new DefaultTimeLine("prh", "Primefaces Release History");
        cal.set(2011, Calendar.MARCH, 10);
        timeline.addEvent(new DefaultTimelineEvent("Primefaces-Extensions 0.1", cal.getTime()));
        cal.set(2012, Calendar.JANUARY, 23);
        timeline.addEvent(new DefaultTimelineEvent("Primefaces-Extensions 0.2.0", cal.getTime()));
        cal.set(2012, Calendar.FEBRUARY, 2);
        timeline.addEvent(new DefaultTimelineEvent("Primefaces Extensions 0.3.0", cal.getTime()));
        cal.set(2012, Calendar.FEBRUARY, 16);
        timeline.addEvent(new DefaultTimelineEvent("Primefaces-Extensions 0.4.0", cal.getTime()));
        cal.set(2012, Calendar.APRIL, 10);
        timeline.addEvent(new DefaultTimelineEvent("Primefaces-Extensions 0.5.0", cal.getTime()));
        cal.set(2012, Calendar.APRIL, 19);
        timeline.addEvent(new DefaultTimelineEvent("Primefaces-Extensions 0.5.1", cal.getTime()));
        cal.set(2012, Calendar.JULY, 26);
        timeline.addEvent(new DefaultTimelineEvent("Primefaces-Extensions 0.6.0", cal.getTime()));
        timelines.add(timeline);
    }

    public List<Timeline> getTimelines() {
        return timelines;
    }

    public String getEventStyle() {
        return eventStyle;
    }

    public void setEventStyle(String eventStyle) {
        this.eventStyle = eventStyle;
    }

    public String getAxisPosition() {
        return axisPosition;
    }

    public void setAxisPosition(String axisPosition) {
        this.axisPosition = axisPosition;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter12/TooltipsController.java
package org.primefaces.cookbook.controller.chapter12;

import java.io.Serializable;

import java.util.Date;
import java.util.Iterator;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;


/**
 * TooltipsController
 *
 * @author Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
@ManagedBean
@ViewScoped
public class TooltipsController implements Serializable {

    private String name;
    private Date birthDate;
    private int children;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getBirthDate() {
        return birthDate;
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    public int getChildren() {
        return children;
    }

    public void setChildren(int children) {
        this.children = children;
    }

    public String getErrorMessage(String clientId) {
        FacesContext fc = FacesContext.getCurrentInstance();
        Iterator<FacesMessage> iter = fc.getMessages(clientId);
        if (iter.hasNext()) {
            return iter.next().getDetail();
        }

        return "";
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter12/TriStateCheckBoxController.java
package org.primefaces.cookbook.controller.chapter12;

import java.io.Serializable;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;


/**
 * TriStateCheckBoxController
 *
 * @author Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
@ManagedBean
@ViewScoped
public class TriStateCheckBoxController implements Serializable {

    private String value1;
    private String value2;
    private String value3;
    private String value4;

    public TriStateCheckBoxController() {
        value1 = "2";
        value4 = "1";
    }

    public String getValue1() {
        return value1;
    }

    public void setValue1(String value1) {
        this.value1 = value1;
    }

    public String getValue2() {
        return value2;
    }

    public void setValue2(String value2) {
        this.value2 = value2;
    }

    public String getValue3() {
        return value3;
    }

    public void setValue3(String value3) {
        this.value3 = value3;
    }

    public String getValue4() {
        return value4;
    }

    public void setValue4(String value4) {
        this.value4 = value4;
    }

    public void addMessage() {
        FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "State has been changed",
                "State is = " + value2);
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }
}

src/main/webapp/views/chapter12/codeMirror.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:pe="http://primefaces.org/ui/extensions"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">

        <h3 style="margin-top:0">Server-side code completion</h3>
        
        <pe:codeMirror id="codeMirror1"
                       mode="#{codeMirrorController.mode}"
                       widgetVar="myCodeMirror"
                       theme="eclipse" value="#{codeMirrorController.content}"
                       lineNumbers="true"
                       completeMethod="#{codeMirrorController.complete}"
                       extraKeys="{'Ctrl-Space': function(cm){myCodeMirror.complete();}}"/>
        
        <h3 style="margin-top:20px">JavaScript code completion</h3>
        
        <pe:codeMirror id="codeMirror2" mode="#{codeMirrorController.mode}"
                       theme="eclipse" value="#{codeMirrorController.content}"
                       lineNumbers="true"
                       extraKeys="{'Ctrl-Space': function(cm){CodeMirror.simpleHint(cm, CodeMirror.javascriptHint);}}"/>
        
        <p:commandButton actionListener="#{codeMirrorController.changeMode}"
                         update="codeMirror1 codeMirror2"
                         value="Change mode with AJAX" style="margin-top:10px;"/>

    </ui:define>
</ui:composition>

src/main/webapp/views/chapter12/dynaForm.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:pe="http://primefaces.org/ui/extensions"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">

        <h:panelGroup id="dynaFormGroup">
            <p:messages id="messages" showSummary="true"/>
        
            <pe:dynaForm id="dynaForm" value="#{dynaFormController.model}" var="data">
                <pe:dynaFormControl type="input" for="txt">
                    <p:inputText id="txt" value="#{data.value}" required="#{data.required}"/>
                </pe:dynaFormControl>
                <pe:dynaFormControl type="calendar" for="cal" styleClass="calendar">
                    <p:calendar id="cal" value="#{data.value}"
                                required="#{data.required}" showOn="button"/>
                </pe:dynaFormControl>
                <pe:dynaFormControl type="select" for="sel" styleClass="select">
                    <p:selectOneMenu id="sel" value="#{data.value}" required="#{data.required}">
                        <f:selectItems value="#{dynaFormController.languages}"/>
                    </p:selectOneMenu>
                </pe:dynaFormControl>
                <pe:dynaFormControl type="textarea" for="tarea">
                    <p:inputTextarea id="tarea" value="#{data.value}"
                                     required="#{data.required}" autoResize="false"/>
                </pe:dynaFormControl>
                <pe:dynaFormControl type="rating" for="rat">
                    <p:rating id="rat" value="#{data.value}" required="#{data.required}"/>
                </pe:dynaFormControl>
        
                <f:facet name="buttonBar">
                    <p:commandButton value="Submit" action="#{dynaFormController.submitForm}"
                                     process="dynaForm"
                                     update=":mainForm:dynaFormGroup :mainForm:inputValues"
                                     oncomplete="handleComplete(xhr, status, args)"/>
                    <p:commandButton type="reset" value="Reset" style="margin-left: 5px;"/>
                </f:facet>
            </pe:dynaForm>
        </h:panelGroup>
        
        <p:dialog header="Input values" widgetVar="inputValuesWidget">
            <p:dataList id="inputValues" value="#{dynaFormController.bookProperties}"
                        var="bookProperty" style="margin:10px;">
                <h:outputText value="#{bookProperty.name}: #{bookProperty.formattedValue}"
                              style="margin-right: 10px;"/>
            </p:dataList>
        </p:dialog>
        
        <h:outputScript id="dynaFormScript" target="body">
            /* <![CDATA[ */
            function handleComplete(xhr, status, args) {
                if(args && args.isValid) {
                    inputValuesWidget.show();
                } else {
                    inputValuesWidget.hide();
                }
            }
            /* ]]> */
        </h:outputScript>

    </ui:define>
    
    <ui:define name="appResources">
        <h:outputStylesheet library="css" name="chapter12/dynaForm.css"/>
    </ui:define>    
</ui:composition>

src/main/webapp/views/chapter12/inputNumber.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:pe="http://primefaces.org/ui/extensions"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">

        <h:panelGrid columns="3">
            <h:panelGroup style="font-weight:bold;">Input Number</h:panelGroup>
            <h:panelGroup style="font-weight:bold;">Double Value</h:panelGroup>
            <h:panelGroup style="font-weight:bold;">Description</h:panelGroup>
        
            <pe:inputNumber id="input1" value="#{inputNumberController.input1}">
                <p:ajax event="blur" update="valueInput1"/>
            </pe:inputNumber>
            <p:inputText id="valueInput1" disabled="true"
                         value="#{inputNumberController.input1}"/>
            <h:outputText value="Without configuration."/>
        
            <pe:inputNumber id="input2" value="#{inputNumberController.input2}"
                            symbol=" CHF" symbolPosition="s"
                            decimalSeparator="," thousandSeparator=".">
                <p:ajax event="blur" update="valueInput2"/>
            </pe:inputNumber>
            <p:inputText id="valueInput2" disabled="true"
                         value="#{inputNumberController.input2}"/>
            <h:outputText value="Currency symbol and decimal / thousand separators."/>
        
            <pe:inputNumber id="input3" value="#{inputNumberController.input3}"
                            minValue="-1000.999" maxValue="1000">
                <p:ajax event="blur" update="valueInput3"/>
            </pe:inputNumber>
            <p:inputText id="valueInput3" disabled="true"
                         value="#{inputNumberController.input3}"/>
            <h:outputText value="Maximun and minimum values (-1000.999 to 1000.000)."/>
        
            <pe:inputNumber id="input4" decimalPlaces="6"
                            value="#{inputNumberController.input4}">
                <p:ajax event="blur" update="valueInput4"/>
            </pe:inputNumber>
            <p:inputText id="valueInput4" disabled="true"
                         value="#{inputNumberController.input4}"/>
            <h:outputText value="Custom decimal places."/>
        </h:panelGrid>

    </ui:define>
</ui:composition>

src/main/webapp/views/chapter12/messagesTooltips.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:pe="http://primefaces.org/ui/extensions"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">

        <h:panelGrid id="details" columns="2" columnClasses="formLabel,formEdit">
            <p:outputLabel for="name" value="Name (required)"/>
            <p:inputText id="name" value="#{tooltipsController.name}" required="true"
                         title="#{component.valid ? '' : tooltipsController.getErrorMessage(component.clientId)}"/>
        
            <p:outputLabel for="date" value="Birth Date (date)"/>
            <p:inputText id="date" value="#{tooltipsController.birthDate}"
                         title="#{component.valid ? '' : tooltipsController.getErrorMessage(component.clientId)}">
                <f:convertDateTime pattern="dd.MM.yyyy"/>
            </p:inputText>
        
            <p:outputLabel for="children" value="Children (number)"/>
            <p:inputText id="children" value="#{tooltipsController.children}"
                         title="#{component.valid ? '' : tooltipsController.getErrorMessage(component.clientId)}">
                <f:validateLength maximum="1"/>
            </p:inputText>
        
        </h:panelGrid>
        
        <p:commandButton value="Submit" process="details" update="details" style="margin-top: 10px;"/>
        
        <pe:tooltip global="true" myPosition="left center"
                    atPosition="right center" forSelector=".ui-state-error"/>

    </ui:define>
</ui:composition>

src/main/webapp/views/chapter12/remoteCommand.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:pe="http://primefaces.org/ui/extensions"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">

        <p:growl id="growl" showDetail="true"/>
        
        <pe:remoteCommand id="applyDataCommand" name="applyData"
                          process="@this" update="growl"
                          actionListener="#{remoteCommandController.printMethodParams}">
            <pe:methodSignature parameters="java.lang.String,
                                            java.util.Date,
                                            org.primefaces.cookbook.model.chapter12.Circle"/>
            <pe:methodParam name="subject"/>
            <pe:methodParam name="date">
                <f:convertDateTime type="both" dateStyle="short" locale="en"/>
            </pe:methodParam>
            <pe:methodParam name="circle">
                <pe:convertJson/>
            </pe:methodParam>
        </pe:remoteCommand>
        
        <script type="text/javascript">
            circle = {
                radius:50,
                backgroundColor:"#FF0000",
                borderColor:"#DDDDDD",
                scaleFactor:1.2
            };
            circle2 = {
                radius:32,
                backgroundColor:"#FF0320",
                borderColor:"#DDFFFD",
                scaleFactor:1.6
            };
        </script>
        
        <p:commandButton value="Apply Data" type="button"
                         onclick="applyData('hello world', '5/14/07 12:55:42 PM', JSON.stringify(circle))"/>
        <p:commandButton value="Apply Second Data" type="button"
                         onclick="applyData('hello user', '7/11/01 11:55:42 PM', JSON.stringify(circle2))"/>


    </ui:define>
</ui:composition>