src/main/java/org/primefaces/cookbook/model/chapter3/Car.java
package org.primefaces.cookbook.model.chapter3;

import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 7/9/12
 */
public class Car implements Serializable {

    public String name;
    public int year;

    public Car(String name, int year) {
        this.name = name;
        this.year = year;
    }

    public String getName() {
        return name;
    }

    public int getYear() {
        return year;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setYear(int year) {
        this.year = year;
    }

    @Override
    public String toString() {
        return getName();
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/AutoCompleteController.java
package org.primefaces.cookbook.controller.chapter3;


import org.primefaces.cookbook.converter.CarConverter;
import org.primefaces.cookbook.model.chapter3.Car;
import org.primefaces.cookbook.utils.MessageUtil;
import org.primefaces.event.SelectEvent;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/**
 * User: mertcaliskan
 * Date: 6/11/12
 */
@ManagedBean
@ViewScoped
public class AutoCompleteController implements Serializable {
    
    private String txt1;
    private Car selectedCar;
    private List<String> selectedTexts;

    public String getTxt1() {
        return txt1;
    }

    public void setTxt1(String txt1) {
        this.txt1 = txt1;
    }

    public Car getSelectedCar() {
        return selectedCar;
    }

    public void setSelectedCar(Car selectedCar) {
        this.selectedCar = selectedCar;
    }

    public List<String> getSelectedTexts() {
        return selectedTexts;
    }

    public void setSelectedTexts(List<String> selectedTexts) {
        this.selectedTexts = selectedTexts;
    }

    public List<Car> completeCar(String input) {
        List<Car> suggestions = new ArrayList<Car>();
        Set<String> keys = CarConverter.cars.keySet();

        for (String key : keys) {
            if (key.startsWith(input)) {
                suggestions.add(CarConverter.cars.get(key));
            }
        }
        return suggestions;
    }

    public void handleSelect(SelectEvent event) {
        Object selectedObject = event.getObject();
        MessageUtil.addInfoMessage("selected.object", selectedObject);
    }

    public List<String> complete(String input) {
        List<String> result = new ArrayList<String>();

        for (int i = 0; i < 10; i++) {
            result.add(input + i);
        }

        return result;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/CalendarController.java
package org.primefaces.cookbook.controller.chapter3;

import org.apache.commons.lang3.time.DateUtils;
import org.primefaces.cookbook.utils.MessageUtil;
import org.primefaces.event.DateSelectEvent;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;
import java.util.Date;

/**
 * User: mertcaliskan
 * Date: 6/28/12
 */
@ManagedBean
@ViewScoped
public class CalendarController implements Serializable {

    private Date date;

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }
    
    public Date getYesterday() {
        return DateUtils.addDays(new Date(), -1);
    }

    public Date getTomorrow() {
        return DateUtils.addDays(new Date(), 1);
    }

    public void onDateSelect(DateSelectEvent event) {
        Date date = event.getDate();
        MessageUtil.addInfoMessage("selected.date", date);
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/EditorController.java
package org.primefaces.cookbook.controller.chapter3;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 6/30/12
 */
@ManagedBean
@ViewScoped
public class EditorController implements Serializable {
    
    private String text;

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/InputMaskController.java
package org.primefaces.cookbook.controller.chapter3;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 6/11/12
 */
@ManagedBean
@ViewScoped
public class InputMaskController implements Serializable {

    private String phone;
    private String phoneExt;
    private String productKey;

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPhoneExt() {
        return phoneExt;
    }

    public void setPhoneExt(String phoneExt) {
        this.phoneExt = phoneExt;
    }

    public String getProductKey() {
        return productKey;
    }

    public void setProductKey(String productKey) {
        this.productKey = productKey;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/InputTextAreaController.java
package org.primefaces.cookbook.controller.chapter3;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 6/25/12
 */
@ManagedBean
@ViewScoped
public class InputTextAreaController implements Serializable {
    
    private String value;

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/PasswordController.java
package org.primefaces.cookbook.controller.chapter3;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 7/19/12
 */
@ManagedBean
@ViewScoped
public class PasswordController implements Serializable {
    
    private String password;

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/RadioSelectionController.java
package org.primefaces.cookbook.controller.chapter3;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 6/30/12
 */
@ManagedBean
@ViewScoped
public class RadioSelectionController implements Serializable {
}

src/main/java/org/primefaces/cookbook/controller/chapter3/RatingController.java
package org.primefaces.cookbook.controller.chapter3;

import org.primefaces.cookbook.utils.MessageUtil;
import org.primefaces.event.RateEvent;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 7/23/12
 */
@ManagedBean
@ViewScoped
public class RatingController implements Serializable {
    
    private Integer rate;

    public Integer getRate() {
        return rate;
    }

    public void setRate(Integer rate) {
        this.rate = rate;
    }

    public void handleRate(RateEvent rateEvent) {
        Integer rate = (Integer) rateEvent.getRating();
        MessageUtil.addInfoMessage("rating.selected", rate);
    }

    public void cancelRate() {
        MessageUtil.addInfoMessage("rating.cancelled");
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/SelectCheckboxController.java
package org.primefaces.cookbook.controller.chapter3;

import org.primefaces.cookbook.utils.MessageUtil;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;
import java.util.List;

/**
 * User: mertcaliskan
 * Date: 6/26/12
 */
@ManagedBean
@ViewScoped
public class SelectCheckboxController implements Serializable {

    private boolean selectedValue;

    private List<String> selectedCountries;

    public boolean isSelectedValue() {
        return selectedValue;
    }

    public void setSelectedValue(boolean selectedValue) {
        this.selectedValue = selectedValue;
    }

    public List<String> getSelectedCountries() {
        return selectedCountries;
    }

    public void setSelectedCountries(List<String> selectedCountries) {
        this.selectedCountries = selectedCountries;
    }

    public void addMessage() {
        String summaryKey = selectedValue ? "checkbox.checked" : "checkbox.unchecked";

        MessageUtil.addInfoMessage(summaryKey);
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/SliderController.java
package org.primefaces.cookbook.controller.chapter3;

import org.primefaces.cookbook.utils.MessageUtil;
import org.primefaces.event.SlideEndEvent;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 7/1/12
 */
@ManagedBean
@ViewScoped
public class SliderController implements Serializable {

    private int intValue = 0;

    public int getIntValue() {
        return intValue;
    }

    public void setIntValue(int intValue) {
        this.intValue = intValue;
    }

    public void onSlideEnd(SlideEndEvent event) {
        int value = event.getValue();
        MessageUtil.addInfoMessage("selected.sliderValue", value);
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/SpinnerController.java
package org.primefaces.cookbook.controller.chapter3;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 7/1/12
 */
@ManagedBean
@ViewScoped
public class SpinnerController implements Serializable {

    private int intValue = 0;
    private int intValue2 = 0;
    private double doubleValue = 0.0;

    public int getIntValue() {
        return intValue;
    }

    public void setIntValue(int intValue) {
        this.intValue = intValue;
    }

    public int getIntValue2() {
        return intValue2;
    }

    public void setIntValue2(int intValue2) {
        this.intValue2 = intValue2;
    }

    public double getDoubleValue() {
        return doubleValue;
    }

    public void setDoubleValue(double doubleValue) {
        this.doubleValue = doubleValue;
    }
}

src/main/webapp/views/chapter3/autoComplete.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Auto Suggestion with AutoComplete</h3>
        <p:growl id="growl"/>
        <h:panelGrid columns="2" cellpadding="5">
            <h:outputText value="Simple" />
            <p:autoComplete id="simple" value="#{autoCompleteController.txt1}" completeMethod="#{autoCompleteController.complete}" />

            <h:outputText value="POJO Support &lt;br/&gt; (Name cars like: Golf, Jetta, CC, Passat, Polo, Scirocco, Touareg)" escape="false" />
            <p:autoComplete id="carPOJO" value="#{autoCompleteController.selectedCar}" completeMethod="#{autoCompleteController.completeCar}"
                            var="car" itemLabel="#{car.name}" itemValue="#{car}" forceSelection="true">
                <f:converter converterId="org.primefaces.cookbook.converter.CarConverter" />
                <p:column>
                    <p:graphicImage value="/resources/images/autocomplete/#{car.name}.png" width="80" height="50"/>
                </p:column>
                <p:column>#{car.name}</p:column>
            </p:autoComplete>

            <h:outputText value="Instant AJAX Selection" />
            <p:autoComplete id="simpleItemSelect" value="#{autoCompleteController.txt1}" completeMethod="#{autoCompleteController.complete}">
                <p:ajax event="itemSelect" listener="#{autoCompleteController.handleSelect}" update="growl" />
            </p:autoComplete>

            <h:outputText value="Multiple Selection" />
            <p:autoComplete id="multipleSelect" value="#{autoCompleteController.selectedTexts}" completeMethod="#{autoCompleteController.complete}" multiple="true" />

        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter3/calendar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Basic and Advanced Calendar Scenarios</h3>
        <p:growl id="growl"/>
        <h:panelGrid columns="2" cellpadding="5">
            <h:outputText value="Basic Selection" />
            <p:calendar value="#{calendarController.date}" />

            <h:outputText value="With Inline Mode" />
            <p:calendar value="#{calendarController.date}" mode="inline" />

            <h:outputText value="With Paging" />
            <p:calendar id="paging" value="#{calendarController.date}" pages="3" />

            <h:outputText value="With Show on" />
            <p:calendar id="showOn" value="#{calendarController.date}" showOn="button" />

            <h:outputText value="Date Selection with Restricted Date Range" />
            <p:calendar id="restrictedDates" value="#{calendarController.date}" mode="inline"
                        mindate="#{calendarController.yesterday}"
                        maxdate="#{calendarController.tomorrow}" />

            <h:outputText value="Calendar With Manual Input Disabled" />
            <p:calendar id="readOnlyInputCalendar" value="#{calendarController.date}" readonlyInput="true" />

            <h:outputText value="With Bounce Effect" />
            <p:calendar id="effectCalendar" value="#{calendarController.date}" effect="bounce" effectDuration="slow" />

            <h:outputText value="AJAX update with Calendar" />
            <p:calendar id="ajaxCalendar" value="#{calendarController.date}" mode="inline">
                <p:ajax event="dateSelect" listener="#{calendarController.onDateSelect}" update="growl" />
            </p:calendar>

            <h:outputText value="Picking Time with Calendar" />
            <p:calendar id="timeCalendar" value="#{calendarController.date}" pattern="dd/MM/yyyy HH:mm:ss" />

        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter3/editor.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Rich Text Editing with the Editor</h3>
        <h:panelGrid columdns="2" cellpadding="5">
            <h:outputText value="Default Editor" />
            <p:editor value="#{editorController.text}" />

            <h:outputText value="Editor with Custom Controls" />
            <p:editor value="#{editorController.text}" controls="bold italic strikethrough" />

            <h:outputText value="Clearing Contents of Editor" />
            <h:panelGroup>
                <p:editor value="#{editorController.text}" widgetVar="editorClear" />
                <p:commandButton type="button" value="Clear" onclick="editorClear.clear()" icon="ui-icon-close" />
            </h:panelGroup>

            <h:outputText value="Selecting all of the text in Editor" />
            <h:panelGroup>
                <p:editor value="#{editorController.text}" widgetVar="editorSelect" />
                <p:commandButton type="button" value="Select" onclick="editorSelect.selectAll()" />
            </h:panelGroup>

            <h:outputText value="Editor inside Dialog Box" />
            <h:panelGroup>
                <p:dialog widgetVar="editorDialog" modal="true">
                    <p:editor />
                </p:dialog>
                <p:commandButton value="Show" onclick="editorDialog.show()" />
            </h:panelGroup>

        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter3/inPlaceEditor.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Advanced Editing with in-place Editor</h3>
        <h:panelGrid columdns="2" cellpadding="5">

            <h:outputText value="Basic in-place Editing" />
            <p:inplace>
                <h:inputText value="Edit Me!" />
            </p:inplace>
            <hr/>

            <h:outputText value="in-place Editing with Drop Down" />
            <p:inplace label="Countries">
                <h:selectOneMenu>
                    <f:selectItem itemLabel="Turkey" itemValue="Turkey" />
                    <f:selectItem itemLabel="Germany" itemValue="Germany" />
                </h:selectOneMenu>
            </p:inplace>
            <hr/>

            <h:outputText value="in-place Editing with Label" />
            <p:inplace label="My Input Field">
                <h:inputText value="Edit Me!" />
            </p:inplace>
            <hr/>

            <h:outputText value="in-place Editing with Empty Label" />
            <p:inplace emptyLabel="My Empty Input Field">
                <h:inputText value="" />
            </p:inplace>
            <hr/>

            <h:outputText value="in-place Editing with editor='true'" />
            <p:inplace editor="true">
                <h:inputText value="Edit Me!" />
            </p:inplace>
            <hr/>

            <h:outputText value="in-place Editing with slide effect" />
            <p:inplace effect="slide">
                <h:inputText value="Edit Me!" />
            </p:inplace>
            <hr/>

            <h:outputText value="in-place Editing with slow slide effect" />
            <p:inplace effect="slide" effectSpeed="slow">
                <h:inputText value="Edit Me!" />
            </p:inplace>
            <hr/>

        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter3/inputMask.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Formatted input with InputMask</h3>
        <h:panelGrid columns="2" cellpadding="5">
            <h:outputText value="Phone number with numeric mask" />
            <p:inputMask value="#{inputMaskController.phone}" mask="(999) 999-9999" />

            <h:outputText value="Product key with Alphabetic mask" />
            <p:inputMask value="#{inputMaskController.productKey}" mask="a999-a9" />

            <h:outputText value="Phone number with Placeholder" />
            <p:inputMask value="#{inputMaskController.phone}" mask="(999) 999-9999" placeHolder="X" />

            <h:outputText value="Product key with Alphanumeric mask" />
            <p:inputMask value="#{inputMaskController.productKey}" mask="a*-999-a999" />

            <h:outputText value="Phone number with optional extension" />
            <p:inputMask value="#{inputMaskController.phoneExt}" mask="(999) 999-9999? x99999" />
        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter3/inputTextArea.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Usable Features of InputTextArea</h3>
        <h:panelGrid columns="2" cellpadding="5">
            <h:outputText value="Basic InputTextArea:" />
            <p:inputTextarea value="#{inputTextAreaController.value}" />

            <h:outputText value="Text Area with auto resizing:" />
            <p:inputTextarea value="#{inputTextAreaController.value}" autoResize="true"/>

            <h:outputText value="Text Area with remaining character count:" />
            <h:panelGroup>
                <p:inputTextarea value="#{inputTextAreaController.value}" counter="display"
                                 maxlength="20" counterTemplate="{0} characters remaining" />
                <br/>
                <h:outputText id="display" />
            </h:panelGroup>
        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter3/password.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Enhanced Password Input</h3>
        <p:growl id="growl"/>
        <h:panelGrid columns="2" cellpadding="5">
            <h:outputText value="Basic Password Input" />
            <p:password value="#{passwordController.password}" />

            <h:outputText value="Password Input with Indicator" />
            <p:password id="feedback" value="#{passwordController.password}" feedback="true" />

            <h:outputText value="Password Input with Inline Indicator" />
            <p:password id="feedbackInline" value="#{passwordController.password}" feedback="true" inline="true" />

            <h:outputText value="Password Input with L10n" />
            <p:password id="passwordL10n" value="#{passwordController.password}" feedback="true"
                        promptLabel="#{msg['password.promptLabel']}"
                        weakLabel="#{msg['password.weakLabel']}"
                        goodLabel="#{msg['password.goodLabel']}"
                        strongLabel="#{msg['password.strongLabel']}"/>

            <h:outputText value="Password Input with Match Mode" />
            <h:panelGrid id="passwords" columns="1">
                <p:messages id="messages" showDetail="true" />
                <p:password id="passwordMatch1" value="#{passwordController.password}" match="passwordMatch2" />
                <p:password id="passwordMatch2" value="#{passwordController.password}" />
                <p:commandButton update="passwords" value="Save" />
            </h:panelGrid>

        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter3/rating.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Star Based Rating Input</h3>
        <p:growl id="growl"/>
        <h:panelGrid columns="2" cellpadding="5">
            <h:outputText value="Basic Rating" />
            <p:rating value="#{ratingController.rate}" />

            <h:outputText value="Rating with 10 stars" />
            <p:rating value="#{ratingController.rate}" stars="10" />

            <h:outputText value="Instant AJAX Selection" />
            <p:rating id="instantRating" value="#{ratingController.rate}">
                <p:ajax event="rate" listener="#{ratingController.handleRate}" update="growl" />
                <p:ajax event="cancel" listener="#{ratingController.cancelRate}" update="growl" />
            </p:rating>
        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter3/selectBooleanCheckboxSelectManyCheckbox.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <p:growl id="growl"/>
        <h3 style="margin-top:0">Discovering SelectBooleanCheckbox and SelectManyCheckbox</h3>
        <h:panelGrid columns="2" cellpadding="5">
            <h:outputText value="Basic SelectBooleanCheckbox" />
            <p:selectBooleanCheckbox value="#{selectCheckboxController.selectedValue}" />

            <h:outputText value="Selection with Custom Label" />
            <p:selectBooleanCheckbox value="#{selectCheckboxController.selectedValue}" itemLabel="#{msg['selectBooleanCheckbox.label']}" />

            <h:outputText value="Getting Selection via JavaScript" />
            <h:panelGroup>
                <p:selectBooleanCheckbox value="#{selectCheckboxController.selectedValue}" widgetVar="mySelection" />
                <p:commandLink value="Alert Selection" onclick="alert(mySelection.isChecked());" />
            </h:panelGroup>

            <h:outputText value="Selection with Ajax Behavior" />
            <p:selectBooleanCheckbox value="#{selectCheckboxController.selectedValue}">
                <p:ajax update="growl" listener="#{selectCheckboxController.addMessage}" />
            </p:selectBooleanCheckbox>

            <h:outputText value="Basic SelectManyCheckbox" />
            <p:selectManyCheckbox value="#{selectCheckboxController.selectedCountries}">
                <f:selectItem itemLabel="Turkey" itemValue="Turkey" />
                <f:selectItem itemLabel="Germany" itemValue="Germany" />
                <f:selectItem itemLabel="Switzerland" itemValue="Switzerland" />
            </p:selectManyCheckbox>

            <h:outputText value="SelectManyCheckbox with layout" />
            <p:selectManyCheckbox value="#{selectCheckboxController.selectedCountries}" layout="pageDirection">
                <f:selectItem itemLabel="Turkey" itemValue="Turkey" />
                <f:selectItem itemLabel="Germany" itemValue="Germany" />
                <f:selectItem itemLabel="Switzerland" itemValue="Switzerland" />
            </p:selectManyCheckbox>

        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter3/spinner.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Spinner - Different ways to provide input</h3>
        <h:panelGrid columns="2" cellpadding="5">
            <h:outputText value="Basic Spinner" />
            <p:spinner value="#{spinnerController.intValue}" />

            <h:outputText value="Spinner with Step Factor" />
            <p:spinner value="#{spinnerController.doubleValue}" stepFactor="0.5" />

            <h:outputText value="Spinner with Prefix" />
            <p:spinner value="#{spinnerController.intValue}" prefix="$" />

            <h:outputText value="Spinner with Suffix" />
            <p:spinner value="#{spinnerController.intValue}" suffix="%" />

            <h:outputText value="Spinner with min-max values" />
            <p:spinner value="#{spinnerController.intValue}" suffix="%" min="0" max="100" onkeydown="return false;" />

            <h:outputText value="AJAX update with Spinner" />
            <h:panelGrid columns="2" cellpadding="2">
                <p:spinner id="ajaxSpinner" value="#{spinnerController.intValue2}" >
                    <p:ajax update="output" process="@this" />
                </p:spinner>
                <h:outputText id="output" value="#{spinnerController.intValue2}" />
            </h:panelGrid>

            <h:outputText value="Defining Size of Spinner" />
            <p:spinner value="#{spinnerController.intValue}" size="3" />
        </h:panelGrid>
    </ui:define>
</ui:composition>